# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadtoimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('c_type', models.TextField(blank=True, default=b'', null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'/projectimg')),
                ('img_name', models.TextField(blank=True, default=b'', null=True)),
                ('img_type', models.TextField(blank=True, default=b'', null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
